### ISSUE TITLE
Extra div with empty class

### ISSUE THREAD

**Issue by psordi** [liip/bootstrap-blocks-wordpress-plugin#33]
Hello, first of all, great plugin and great work.
I've just noticed that after a column is created, in the HTML output a new 'div' is inserted.
For example:
`<div class="col-12 col-md-4"><div class="">...</div></div>`
Thanks for your attention.

**Comment by tschortsch** [comment]
Hi @psordi. This is a know issue of the `column` template. It's described in this issue: #31. You'll also find a workaround in the answer. We'll probably will remove the empty div in a next release of the plugin. Such template changes are always a bit critical since they might break current installations.

**Comment by tschortsch** [comment]
This is fixed in version 2.1.0 of the plugin.
