### ISSUE TITLE
Deprecated Wordpress components

### ISSUE THREAD

**Issue by michelebruno** [liip/bootstrap-blocks-wordpress-plugin#36]
Hi, Wordpress gives the following warnings when I open the editor.

![immagine](https://user-images.githubusercontent.com/43304601/75680720-7835e500-5c92-11ea-9be0-ce74f488849c.png)

May anybody update the wordpress import statements?

**Comment by tschortsch** [comment]
Hi @michelebruno. We're aware of the deprecation notices. The problem is that as soon as we update these dependencies we lose the backwards compatibility to older WordPress versions. This is sadly one of the bigger issues in Gutenberg development. We will certainly updates the dependencies as soon as it's needed but we also try to keep the backwards compatibility as long as possible.

**Comment by michelebruno** [comment]
Ok, thank you very much.
