### ISSUE TITLE
Use align-self-* for vertical align instead of using a wrapper

### ISSUE THREAD

**Issue by R33D3M33R** [liip/bootstrap-blocks-wordpress-plugin#84]
Dear developers,

when using the "Change text alignment" option, a wrapper gets added inside the column which seems unnecessary, as bootstrap already has align-self-* utilities which can be used directly on a column: https://getbootstrap.com/docs/4.1/utilities/flex/ or https://getbootstrap.com/docs/5.0/utilities/flex/

Using the align-self-* would thus be much simpler. Please consider changing this.

Best regards,
Andrej

**Comment by tschortsch** [comment]
Hi @R33D3M33R. You are speaking about the "Change vertical alignment of content" option of the column block right? Because in the row block there shouldn't be an additional wrapper (only classes).
This behavior was introduced some time ago to also make the background color fill the whole column if applied. Changing it would be a (bigger) breaking change and we try to avoid those as good as possible.
But you always have the possibility to provide your own template for the blocks by creating a `wp-bootstrap-blocks` folder in your template and add the respecting template there. See: https://github.com/liip/bootstrap-blocks-wordpress-plugin#templates.

**Comment by R33D3M33R** [comment]
Hi @tschortsch,

Thank you for your explanation - I see now that the wrapper is necessary. We have successfully overridden the template, so everything is ok.

Thanks again and best regards,
Andrej
